'use client';

import { useEffect, useState, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { getTopTracks, getTopArtists } from '@/lib/spotify-api';

export default function ReceiptPage() {
  const router = useRouter();
  const receiptRef = useRef<HTMLDivElement>(null);
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [timeRange, setTimeRange] = useState<'short_term' | 'medium_term' | 'long_term'>('medium_term');

  useEffect(() => {
    const token = localStorage.getItem('spotify_access_token');
    
    if (!token) {
      router.push('/');
      return;
    }

    Promise.all([
      getTopTracks(token, timeRange, 10),
      getTopArtists(token, timeRange, 5)
    ])
      .then(([tracks, artists]) => {
        setData({ tracks: tracks.items, artists: artists.items });
      })
      .catch(() => router.push('/'))
      .finally(() => setLoading(false));
  }, [router, timeRange]);

  const handleExport = () => {
    if (!receiptRef.current) return;
    
    // Simple share functionality
    if (navigator.share) {
      navigator.share({
        title: 'My Spotify Receipt',
        text: 'Check out my Spotify listening stats!',
      });
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin w-8 h-8 border-4 border-[var(--accent-primary)] border-t-transparent rounded-full" />
      </div>
    );
  }

  const timeRangeLabel = {
    short_term: 'Last 4 Weeks',
    medium_term: 'Last 6 Months',
    long_term: 'All Time'
  };

  return (
    <div className="min-h-screen p-4">
      <div className="max-w-2xl mx-auto">
        <button
          onClick={() => router.push('/dashboard')}
          className="mb-6 text-sm px-4 py-2 rounded-full"
          style={{ color: 'var(--text-secondary)', border: '1px solid var(--border)' }}
        >
          ← Back
        </button>

        <div className="flex gap-2 mb-6">
          {(['short_term', 'medium_term', 'long_term'] as const).map((range) => (
            <button
              key={range}
              onClick={() => setTimeRange(range)}
              className="px-4 py-2 rounded-full text-sm transition-all"
              style={{
                background: timeRange === range ? 'var(--accent-primary)' : 'var(--surface)',
                color: timeRange === range ? 'white' : 'var(--text-secondary)',
                border: '1px solid var(--border)'
              }}
            >
              {timeRangeLabel[range]}
            </button>
          ))}
        </div>

        <div 
          ref={receiptRef}
          className="p-8 font-mono text-sm"
          style={{ 
            background: 'white',
            color: '#000',
            maxWidth: '400px',
            margin: '0 auto',
            border: '2px dashed #000'
          }}
        >
          <div className="text-center mb-6">
            <div className="text-2xl font-bold mb-2">SPOTIFY RECEIPT</div>
            <div className="text-xs">━━━━━━━━━━━━━━━━━━━━━━━━━━</div>
            <div className="mt-2">{new Date().toLocaleDateString()}</div>
            <div className="text-xs mt-1">{timeRangeLabel[timeRange]}</div>
          </div>

          <div className="mb-6">
            <div className="font-bold mb-2">TOP TRACKS</div>
            {data?.tracks.map((track: any, i: number) => (
              <div key={track.id} className="mb-2">
                <div className="flex justify-between">
                  <span>{i + 1}. {track.name.substring(0, 25)}</span>
                </div>
                <div className="text-xs opacity-60 ml-4">
                  {track.artists[0].name}
                </div>
              </div>
            ))}
          </div>

          <div className="mb-6">
            <div className="font-bold mb-2">TOP ARTISTS</div>
            {data?.artists.map((artist: any, i: number) => (
              <div key={artist.id} className="mb-1">
                {i + 1}. {artist.name}
              </div>
            ))}
          </div>

          <div className="text-center text-xs mt-6 pt-4 border-t-2 border-dashed border-black">
            <div>Generated by Flowtify</div>
            <div className="mt-2">━━━━━━━━━━━━━━━━━━━━━━━━━━</div>
          </div>
        </div>

        <div className="flex justify-center mt-6">
          <button
            onClick={handleExport}
            className="px-6 py-3 rounded-full font-medium"
            style={{ background: 'var(--accent-primary)', color: 'white' }}
          >
            Share Receipt
          </button>
        </div>
      </div>
    </div>
  );
}
